name: CI (test coverage)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    strategy:
      fail-fast: false
      matrix:
        timezone:
          - "America/New_York"
          - "Europe/London"
          - "Asia/Tokyo"
          - "UTC"

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24.14.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set timezone to ${{ matrix.timezone }}
        run: |
          sudo timedatectl set-timezone ${{ matrix.timezone }}
          date

      - name: Run tests in ${{ matrix.timezone }} timezone
        run: |
          pnpm test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5
        if: ${{ matrix.timezone == 'UTC' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: still-forest/proper-date.js
